### ISSUE TITLE
Cannot start iOS device could not find Xcode path

### ISSUE THREAD

**Issue by rades101** [danielpaulus/ios-appium-on-linux#3]
Hi Daniel,
Thanks for a great tutorial. I am trying to setup iOS automation on Ubuntu. 
I did steps that you recommended. 
I can see that iPhone is connected to the docker container with appium 

`# idevice_id -l
00008030-000358EE1A51402E
`
Also runwda worked, here is output:
`{"level":"info","msg":"no udid specified using first device in list","time":"2022-06-16T17:38:05-05:00","udid":"00008030-000358EE1A51402E"}
{"level":"info","msg":"no bundle ids specified, falling back to defaults","time":"2022-06-16T17:38:05-05:00"}
{"bundleid":"com.facebook.WebDriverAgentRunner.xctrunner","level":"info","msg":"Running wda","testbundleid":"com.facebook.WebDriverAgentRunner.xctrunner","time":"2022-06-16T17:38:05-05:00","xctestconfig":"WebDriverAgentRunner.xctest"}
{"bundleID":"com.facebook.WebDriverAgentRunner.xctrunner","channel_id":"com.apple.instruments.server.services.processcontrol","level":"info","msg":"Launching process","time":"2022-06-16T17:38:06-05:00"}
{"channel_id":"com.apple.instruments.server.services.processcontrol","level":"info","msg":"Process started successfully","pid":11501,"time":"2022-06-16T17:38:06-05:00"}
{"level":"info","msg":"2022-06-16 17:38:06.981216-0500 WebDriverAgentRunner-Runner[11501:1060939] Running tests...\n","time":"2022-06-16T17:38:07-05:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_didBeginExecutingTestPlan","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_didBeginInitializingForUITesting","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"Test Suite 'All tests' started at 2022-06-16 17:38:08.445\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"XCTestOutputBarrier","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"Test Suite 'WebDriverAgentRunner.xctest' started at 2022-06-16 17:38:08.446\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"XCTestOutputBarrier","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"Test Suite 'UITestingUITests' started at 2022-06-16 17:38:08.447\nXCTestOutputBarrier","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"    t =      nans Suite Set Up\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testSuite:didStartAt:","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testSuite:didStartAt:","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testSuite:didStartAt:","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:willStartActivity:","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"2022-06-16 17:38:08.466975-0500 WebDriverAgentRunner-Runner[11501:1060939] [User Defaults] Couldn't write values for keys (\n    KeyboardAutocorrection\n) in CFPrefsPlistSource\u003c0x28103ab80\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"2022-06-16 17:38:08.467496-0500 WebDriverAgentRunner-Runner[11501:1060939] [User Defaults] Couldn't write values for keys (\n    \"KeyboardAutocorrection_changedAt\"\n) in CFPrefsPlistSource\u003c0x28103ab80\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"2022-06-16 17:38:08.467954-0500 WebDriverAgentRunner-Runner[11501:1060939] [User Defaults] Couldn't write values for keys (\n    \"KeyboardAutocorrection_buildAtChange\"\n) in CFPrefsPlistSource\u003c0x28103ab80\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"2022-06-16 17:38:08.468398-0500 WebDriverAgentRunner-Runner[11501:1060939] [User Defaults] Couldn't write values for keys (\n    \"KeyboardAutocorrection_previousValue\"\n) in CFPrefsPlistSource\u003c0x28103ab80\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"2022-06-16 17:38:08.468843-0500 WebDriverAgentRunner-Runner[11501:1060939] [User Defaults] Couldn't write values for keys (\n    \"KeyboardAutocorrection_analyzedAt\"\n) in CFPrefsPlistSource\u003c0x28103ab80\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"2022-06-16 17:38:08.479212-0500 WebDriverAgentRunner-Runner[11501:1060939] [User Defaults] Couldn't write values for keys (\n    KeyboardPrediction\n) in CFPrefsPlistSource\u003c0x28103ab80\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"2022-06-16 17:38:08.479725-0500 WebDriverAgentRunner-Runner[11501:1060939] [User Defaults] Couldn't write values for keys (\n    KeyboardShowPredictionBar\n) in CFPrefsPlistSource\u003c0x28103ab80\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"2022-06-16 17:38:08.481527-0500 WebDriverAgentRunner-Runner[11501:1060939] [User Defaults] Couldn't write values for keys (\n    DidShowGestureKeyboardIntroduction\n) in CFPrefsPlistSource\u003c0x28103ab80\u003e (Domain: com.apple.keyboard.preferences, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:didFinishActivity:","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCaseDidStartForTestClass:method:","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"Test Case '-[UITestingUITests testRunner]' started.\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:willStartActivity:","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"XCTestOutputBarrier","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"    t =     0.00s Start Test at 2022-06-16 17:38:08.486\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"    t =     0.00s Set Up\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"2022-06-16 17:38:08.487959-0500 WebDriverAgentRunner-Runner[11501:1060939] Built at Jun 16 2022 16:34:17\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:didFinishActivity:","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:willStartActivity:","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"device called local method","sel":"_XCT_testCase:method:didFinishActivity:","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"2022-06-16 17:38:08.496825-0500 WebDriverAgentRunner-Runner[11501:1060939] ServerURLHere-\u003ehttp://10.40.5.249:8100\u003c-ServerURLHere\n","time":"2022-06-16T17:38:08-05:00"}
{"level":"info","msg":"2022-06-16 17:38:08.497010-0500 WebDriverAgentRunner-Runner[11501:1060960] Using singleton test manager\n","time":"2022-06-16T17:38:08-05:00"}
`

However, once i start tests i am getting  XcodePath error. Could you please take a look and give idea what could be. 
`Appium] Appium v1.22.2 creating new XCUITestDriver (v3.59.0) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "ios",
[debug] [BaseDriver]     "appium:platformVersion": "15.4.1",
[debug] [BaseDriver]     "appium:autoAcceptAlerts": false,
[debug] [BaseDriver]     "appium:automationName": "XCUITest",
[debug] [BaseDriver]     "appium:bundleId": "com.apple.TestFlight",
[debug] [BaseDriver]     "appium:deviceName": "iPhone",
[debug] [BaseDriver]     "appium:newCommandTimeout": 0,
[debug] [BaseDriver]     "appium:udid": "00008030-000358EE1A51402E",
[debug] [BaseDriver]     "appium:wdaLocalPort": 10189,
[debug] [BaseDriver]     "appium:xcodeOrgId": "XXXXXXXXXX",
[debug] [BaseDriver]     "appium:xcodeSigningId": "Developer"
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] Session created with session id: fde22f60-1bea-451f-817b-a8f24de374fa
[debug] [XCUITest] Current user: 'root'
[debug] [XCUITest] Available devices: 00008030-000358EE1A51402E
[debug] [XCUITest] Creating iDevice object with udid '00008030-000358EE1A51402E'
[XCUITest] Determining device to run tests on: udid: '00008030-000358EE1A51402E', real device: true
[XCUITest] Normalized platformVersion capability value '15.4.1' to '15.4'
[Xcode] Finding XcodePath by symlink because Error: spawn xcode-select ENOENT
[Xcode] Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
[debug] [XCUITest] Error: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
[debug] [XCUITest]     at getPathFromSymlink (/usr/lib/node_modules/appium/node_modules/appium-xcode/lib/xcode.js:84:9)
[debug] [XCUITest]     at getVersionWithoutRetry (/usr/lib/node_modules/appium/node_modules/appium-xcode/lib/xcode.js:114:21)
[debug] [XCUITest]     at retry (/usr/lib/node_modules/appium/node_modules/asyncbox/lib/asyncbox.js:43:13)
[debug] [XCUITest]     at Object.getVersion (/usr/lib/node_modules/appium/node_modules/appium-xcode/lib/xcode.js:135:19)
[debug] [XCUITest]     at getAndCheckXcodeVersion (/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:41:15)
[debug] [XCUITest]     at XCUITestDriver.start (/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:350:27)
[debug] [XCUITest]     at XCUITestDriver.createSession (/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:255:7)
[debug] [XCUITest]     at AppiumDriver.createSession (/usr/lib/node_modules/appium/lib/appium.js:387:35)
[XCUITest] Could not determine Xcode version: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
[XCUITest] {}
[DevCon Factory] Releasing connections for 00008030-000358EE1A51402E device on any port number
[DevCon Factory] No cached connections have been found
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1655419132120 (17:38:52 GMT-0500 (Central Daylight Time))
[debug] [W3C] Encountered internal error running command: Error: Could not determine Xcode version: Could not find path to Xcode by symlinks located in /var/db/xcode_select_link, or /usr/share/xcode-select/xcode_dir_link
[debug] [W3C]     at Object.errorAndThrow (/usr/lib/node_modules/appium/node_modules/appium-support/lib/logging.js:94:35)
[debug] [W3C]     at getAndCheckXcodeVersion (/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/utils.js:44:9)
[debug] [W3C]     at XCUITestDriver.start (/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:350:27)
[debug] [W3C]     at XCUITestDriver.createSession (/usr/lib/node_modules/appium/node_modules/appium-xcuitest-driver/lib/driver.js:255:7)
[debug] [W3C]     at AppiumDriver.createSession (/usr/lib/node_modules/appium/lib/appium.js:387:35)
[HTTP] <-- POST /wd/hub/session 500 395 ms - 795
`

Thanks,
Rade

**Comment by fredknight** [comment]
Hi there, I've just run into the same issue. Did you manage to resolve this at all, or is there any word on how this could be fixed?
